
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int SHORT = 27;
  public static final int EQUALS = 17;
  public static final int DOUBLE = 33;
  public static final int LPAREN = 10;
  public static final int GREATER = 15;
  public static final int SEMI = 12;
  public static final int INT = 28;
  public static final int LESS = 13;
  public static final int MINUS = 6;
  public static final int RCBRACKET = 4;
  public static final int RPAREN = 11;
  public static final int NOT = 21;
  public static final int AND = 19;
  public static final int OR = 20;
  public static final int COMMA = 23;
  public static final int CLASS = 2;
  public static final int PLUS = 5;
  public static final int LESSEQ = 14;
  public static final int ASSIGN = 22;
  public static final int IF = 34;
  public static final int ID = 24;
  public static final int EOF = 0;
  public static final int BOOLEAN = 30;
  public static final int RETURN = 36;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int NUMBER = 38;
  public static final int MOD = 9;
  public static final int VOID = 25;
  public static final int BYTE = 26;
  public static final int REAL = 37;
  public static final int TIMES = 7;
  public static final int STRING_VALUE = 41;
  public static final int ELSE = 35;
  public static final int LCBRACKET = 3;
  public static final int FLOAT = 32;
  public static final int LONG = 29;
  public static final int GREATEREQ = 16;
  public static final int STRING = 31;
  public static final int DIFF = 18;
  public static final int FALSE = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "LCBRACKET",
  "RCBRACKET",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LESS",
  "LESSEQ",
  "GREATER",
  "GREATEREQ",
  "EQUALS",
  "DIFF",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "COMMA",
  "ID",
  "VOID",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "BOOLEAN",
  "STRING",
  "FLOAT",
  "DOUBLE",
  "IF",
  "ELSE",
  "RETURN",
  "REAL",
  "NUMBER",
  "TRUE",
  "FALSE",
  "STRING_VALUE"
  };
}

